// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AccessibleModel is an autogenerated mock type for the AccessibleModel type
type AccessibleModel struct {
	mock.Mock
}

type mockConstructorTestingTNewAccessibleModel interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccessibleModel creates a new instance of AccessibleModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccessibleModel(t mockConstructorTestingTNewAccessibleModel) *AccessibleModel {
	mock := &AccessibleModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
