// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "klikdaily-databoard/models"

	mock "github.com/stretchr/testify/mock"

	repositories "klikdaily-databoard/repositories"
)

// AdminUseCaseInterface is an autogenerated mock type for the AdminUseCaseInterface type
type AdminUseCaseInterface struct {
	mock.Mock
}

// CreateAdmin provides a mock function with given fields: admin
func (_m *AdminUseCaseInterface) CreateAdmin(admin models.AdminRequest) repositories.RepositoryResult[models.Admin] {
	ret := _m.Called(admin)

	var r0 repositories.RepositoryResult[models.Admin]
	if rf, ok := ret.Get(0).(func(models.AdminRequest) repositories.RepositoryResult[models.Admin]); ok {
		r0 = rf(admin)
	} else {
		r0 = ret.Get(0).(repositories.RepositoryResult[models.Admin])
	}

	return r0
}

type mockConstructorTestingTNewAdminUseCaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminUseCaseInterface creates a new instance of AdminUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminUseCaseInterface(t mockConstructorTestingTNewAdminUseCaseInterface) *AdminUseCaseInterface {
	mock := &AdminUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
